### ISSUE TITLE
Running test or build fails

### ISSUE THREAD

**Issue by dmohan-intraedge** [aws-solutions/aws-control-tower-customizations#187]
**Describe the bug**
While setting up the project and following the README and executing the commands to run test errors out. Same with the build.

> ./deployment/run-unit-tests.sh

Error Log:
Creating testing-venv...
Rebuilding package locally before testing...
Using python: python3 is /Users/fatman/repos/fatmanaws-control-tower-customizations/testing-venv/bin/python3
Python version: Python 3.12.2
Installing pip
Installing CFCT library
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/fatman/repos/fatmanaws-control-tower-customizations/testing-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/fatman/repos/fatmanaws-control-tower-customizations/testing-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/fatman/repos/fatmanaws-control-tower-customizations/testing-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/b2/hvgz4tyx7ws961ymkskrjnb40000gn/T/pip-build-env-4e_hztbd/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**To Reproduce**
Run through the Readme.

**Expected behavior**

**Please complete the following information about the solution:**
- v2.7.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0089) - customizations-for-aws-control-tower Solution. Version: v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-control-tower-customizations/releases)

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by snebhu3** [comment]
@dmohan-intraedge thanks for reaching out.
This seems to a similar error reported in #183 
Please may you try the workaround mentioned in the issue and retry your workflow?
